use_frameworks!

platform :ios, '10.0'

target 'ZWProgressHUD_Example' do
  pod 'ZWProgressHUD', :path => '../'

  target 'ZWProgressHUD_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
